### ISSUE TITLE
Could not discover tests because of SerializableException

### ISSUE THREAD

**Issue by WaterRabbit** [axodox/AxoTools#107]
### Versions:
VS 2017 Community 15.2 (26430.16)
AxoCover 1.1.228 and 1.1.229

### Issue:

```
> Discovering tests...
| Runner version is 1.1.228.0.
< Could not discover tests!
< SerializableException: Could not load file or assembly 'AxoCover.Native.dll' or one of its dependencies. The specified module could not be found.
<    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
<    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
<    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
<    at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
<    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
<    at AxoCover.Runner.NativeServices.InitializeIfNeeded() in C:\projects\axotools\AxoCover.Runner\NativeServices.cs:line 33
<    at AxoCover.Runner.NativeServices.ExecuteWithFileRedirection(TestAdapterOptions adapterOptions, Action action, Action`2 log) in C:\projects\axotools\AxoCover.Runner\NativeServices.cs:line 18
<    at AxoCover.Runner.TestDiscoveryService.DiscoverTests(TestDiscoveryTask[] discoveryTasks, String runSettingsPath) in C:\projects\axotools\AxoCover.Runner\TestDiscoveryService.cs:line 86
Test discovery finished.
```
```
> Discovering tests...
| Runner version is 1.1.229.0.
< Could not discover tests!
< SerializableException: Could not load file or assembly 'AxoCover.Native.dll' or one of its dependencies. The specified module could not be found.
<    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
<    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
<    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
<    at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
<    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
<    at AxoCover.Runner.NativeServices.InitializeIfNeeded() in C:\projects\axotools\AxoCover.Runner\NativeServices.cs:line 33
<    at AxoCover.Runner.NativeServices.ExecuteWithFileRedirection(TestAdapterOptions adapterOptions, Action action, Action`2 log) in C:\projects\axotools\AxoCover.Runner\NativeServices.cs:line 18
<    at AxoCover.Runner.TestDiscoveryService.DiscoverTests(TestDiscoveryTask[] discoveryTasks, String runSettingsPath) in C:\projects\axotools\AxoCover.Runner\TestDiscoveryService.cs:line 86
Test discovery finished.
```

```
*** Assembly Binder Log Entry  (2017. 07. 22. @ 10:58:42) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Users\id\AppData\Local\Microsoft\VisualStudio\15.0_814e343f\Extensions\xnhcqhdj.s2p\AxoCover.Runner.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = AxoCover.Runner.XmlSerializers, Version=1.1.229.0, Culture=neutral, PublicKeyToken=null, processorArchitecture=MSIL
 (Fully-specified)
LOG: Appbase = file:///C:/Users/id/AppData/Local/Microsoft/VisualStudio/15.0_814e343f/Extensions/xnhcqhdj.s2p/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = AxoCover.Runner.exe
Calling assembly : System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\id\AppData\Local\Microsoft\VisualStudio\15.0_814e343f\Extensions\xnhcqhdj.s2p\AxoCover.Runner.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/Users/id/AppData/Local/Microsoft/VisualStudio/15.0_814e343f/Extensions/xnhcqhdj.s2p/AxoCover.Runner.XmlSerializers.DLL.
LOG: Attempting download of new URL file:///C:/Users/id/AppData/Local/Microsoft/VisualStudio/15.0_814e343f/Extensions/xnhcqhdj.s2p/AxoCover.Runner.XmlSerializers/AxoCover.Runner.XmlSerializers.DLL.
LOG: Attempting download of new URL file:///C:/Users/id/AppData/Local/Microsoft/VisualStudio/15.0_814e343f/Extensions/xnhcqhdj.s2p/x86/AxoCover.Runner.XmlSerializers.DLL.
LOG: Attempting download of new URL file:///C:/Users/id/AppData/Local/Microsoft/VisualStudio/15.0_814e343f/Extensions/xnhcqhdj.s2p/x86/AxoCover.Runner.XmlSerializers/AxoCover.Runner.XmlSerializers.DLL.
LOG: Attempting download of new URL file:///C:/Users/id/AppData/Local/Microsoft/VisualStudio/15.0_814e343f/Extensions/xnhcqhdj.s2p/x64/AxoCover.Runner.XmlSerializers.DLL.
LOG: Attempting download of new URL file:///C:/Users/id/AppData/Local/Microsoft/VisualStudio/15.0_814e343f/Extensions/xnhcqhdj.s2p/x64/AxoCover.Runner.XmlSerializers/AxoCover.Runner.XmlSerializers.DLL.
LOG: Attempting download of new URL file:///C:/Users/id/AppData/Local/Microsoft/VisualStudio/15.0_814e343f/Extensions/xnhcqhdj.s2p/AxoCover.Runner.XmlSerializers.EXE.
LOG: Attempting download of new URL file:///C:/Users/id/AppData/Local/Microsoft/VisualStudio/15.0_814e343f/Extensions/xnhcqhdj.s2p/AxoCover.Runner.XmlSerializers/AxoCover.Runner.XmlSerializers.EXE.
LOG: Attempting download of new URL file:///C:/Users/id/AppData/Local/Microsoft/VisualStudio/15.0_814e343f/Extensions/xnhcqhdj.s2p/x86/AxoCover.Runner.XmlSerializers.EXE.
LOG: Attempting download of new URL file:///C:/Users/id/AppData/Local/Microsoft/VisualStudio/15.0_814e343f/Extensions/xnhcqhdj.s2p/x86/AxoCover.Runner.XmlSerializers/AxoCover.Runner.XmlSerializers.EXE.
LOG: Attempting download of new URL file:///C:/Users/id/AppData/Local/Microsoft/VisualStudio/15.0_814e343f/Extensions/xnhcqhdj.s2p/x64/AxoCover.Runner.XmlSerializers.EXE.
LOG: Attempting download of new URL file:///C:/Users/id/AppData/Local/Microsoft/VisualStudio/15.0_814e343f/Extensions/xnhcqhdj.s2p/x64/AxoCover.Runner.XmlSerializers/AxoCover.Runner.XmlSerializers.EXE.
LOG: All probing URLs attempted and failed.
```

**Comment by axodox** [comment]
Can you please send the list all files in AxoCover's including subfolders (you may use tree /F in cmd). 
Based on the log provided AxoCover is installed in the following directory on your machine:
C:\Users\id\AppData\Local\Microsoft\VisualStudio\15.0_814e343f\Extensions\xnhcqhdj.s2p\

**Comment by WaterRabbit** [comment]
```
C:\Users\id\AppData\Local\Microsoft\VisualStudio\15.0_814e343f\Extensions\xnhcqhdj.s2p>tree /f
Folder PATH listing
Volume serial number is 000000EC 4E73:7BA2
C:.
│   AxoCover.Common.dll
│   AxoCover.Common.pdb
│   AxoCover.Dependencies.dll
│   AxoCover.Dependencies.pdb
│   AxoCover.dll
│   AxoCover.Host-x64.exe
│   AxoCover.Host-x64.exe.config
│   AxoCover.Host-x64.pdb
│   AxoCover.Host-x86.exe
│   AxoCover.Host-x86.exe.config
│   AxoCover.Host-x86.pdb
│   AxoCover.pdb
│   AxoCover.pkgdef
│   AxoCover.Runner.exe
│   AxoCover.Runner.exe.config
│   AxoCover.Runner.pdb
│   catalog.json
│   changelog.txt
│   EasyHook32.dll
│   EasyHook64.dll
│   extension.vsixmanifest
│   license.txt
│   manifest.json
│   Microsoft.Practices.ServiceLocation.dll
│   Microsoft.Practices.Unity.Configuration.dll
│   Microsoft.Practices.Unity.dll
│   Microsoft.Practices.Unity.RegistrationByConvention.dll
│   Newtonsoft.Json.dll
│
├───MSTestAdapter
│       Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll
│       Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll
│       Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.dll
│       Microsoft.VisualStudio.TestPlatform.TestFramework.dll
│       Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll
│
├───NUnit2Adapter
│       Mono.Cecil.dll
│       Mono.Cecil.Mdb.dll
│       Mono.Cecil.Pdb.dll
│       Mono.Cecil.Rocks.dll
│       nunit.core.dll
│       nunit.core.interfaces.dll
│       nunit.util.dll
│       NUnit.VisualStudio.TestAdapter.dll
│
├───NUnit3Adapter
│       Mono.Cecil.dll
│       Mono.Cecil.Mdb.dll
│       Mono.Cecil.Pdb.dll
│       Mono.Cecil.Rocks.dll
│       nunit.engine.api.dll
│       nunit.engine.dll
│       NUnit3.TestAdapter.dll
│
├───OpenCover
│   │   Autofac.Configuration.dll
│   │   Autofac.dll
│   │   CrashReporter.NET.dll
│   │   Gendarme.Framework.dll
│   │   Gendarme.Rules.Maintainability.dll
│   │   log4net.config
│   │   log4net.dll
│   │   Mono.Cecil.dll
│   │   Mono.Cecil.Mdb.dll
│   │   Mono.Cecil.Pdb.dll
│   │   OpenCover.Console.exe
│   │   OpenCover.Console.exe.config
│   │   OpenCover.Console.pdb
│   │   OpenCover.Extensions.dll
│   │   OpenCover.Extensions.pdb
│   │   OpenCover.Framework.dll
│   │   OpenCover.Framework.pdb
│   │
│   ├───x64
│   │       OpenCover.Profiler.dll
│   │
│   └───x86
│           OpenCover.Profiler.dll
│
├───ReportGenerator
│       ICSharpCode.NRefactory.CSharp.dll
│       ICSharpCode.NRefactory.dll
│       ReportGenerator.exe
│       ReportGenerator.exe.config
│       ReportGenerator.Reporting.dll
│       ReportGenerator.Reporting.XML
│       ReportGenerator.XML
│
├───Resources
│       icon.png
│       preview.png
│
├───TestPlatform
│       Microsoft.VisualStudio.TestPlatform.ObjectModel.dll
│
├───x64
│       AxoCover.Native.dll
│       EasyHook64.dll
│
├───x86
│       AxoCover.Native.dll
│       EasyHook32.dll
│
└───xUnitAdapter
        xunit.abstractions.dll
        xunit.assert.dll
        xunit.core.dll
        xunit.execution.desktop.dll
        xunit.runner.reporters.net452.dll
        xunit.runner.utility.net35.dll
        xunit.runner.visualstudio.testadapter.dll
```

**Comment by axodox** [comment]
Is Microsoft Visual C++ Redistributable 2012 installed on your computer? Maybe MSVCR110.dll or MSVCP110.dll is missing.

**Comment by axodox** [comment]
As a workaround you may go to settings and uncheck this:
![image](https://user-images.githubusercontent.com/22882208/28561542-29e09bd6-711f-11e7-9ef1-6a05e0b6035d.png)

**Comment by WaterRabbit** [comment]
Thank you for the help. It was the missing Microsoft Visual C++ Redistributable 2012.

**Comment by lextm** [comment]
It seems that this should be made an FAQ. 

I also met this issue initially. It happened to be resolved when I tried to compile the source code, as I installed Visual Studio 2012 Express (which contains the C++ redistributable).

**Comment by axodox** [comment]
Added a warning to the output with a link to the redistributable, I might add something fancier later.
