### ISSUE TITLE
SerializableException at Visual Studio startup when .axoCover\settings.json is a read-only file

### ISSUE THREAD

**Issue by NeilJustice** [axodox/AxoTools#108]
Thank you Peter for writing AxoCover. Great logo, UI design, features, and potential.

I'm seeing at startup of VS2017 Update 2 with AxoCover 1.1.2.6 (also referred to as version 1.1.243.0 in AxoCover Settings), the AxoCover Output window populates itself with fifteen SerializableException error messages and stacktraces when the .axoCover\settings.json file is marked read-only, as Team Foundation Server is fond of doing. I could understand a SerializableException upon editing an AxoCover setting with settings.json marked read-only, but at Visual Studio startup time one might expect settings.json to just be read instead of written to.

AxoCover Output window text at startup:

Could not save solution settings to: C:\Future\PostBuildEventChecker\.axoCover\settings.json.
SerializableException: Access to the path 'C:\Future\PostBuildEventChecker\.axoCover\settings.json' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at AxoCover.Models.Options.TrySaveTo(String path) in C:\projects\axotools\AxoCover\Models\Options.cs:line 294
Could not save solution settings to: C:\Future\PostBuildEventChecker\.axoCover\settings.json.
SerializableException: Access to the path 'C:\Future\PostBuildEventChecker\.axoCover\settings.json' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at AxoCover.Models.Options.TrySaveTo(String path) in C:\projects\axotools\AxoCover\Models\Options.cs:line 294
...
12 identical SerializableException messages
...
Could not save solution settings to: C:\Future\PostBuildEventChecker\.axoCover\settings.json.
SerializableException: Access to the path 'C:\Future\PostBuildEventChecker\.axoCover\settings.json' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at AxoCover.Models.Options.TrySaveTo(String path) in C:\projects\axotools\AxoCover\Models\Options.cs:line 294

**Comment by axodox** [comment]
I think I know where this problem is originating. I will add a fix at the weekend.

**Comment by axodox** [comment]
Fix released.
