### ISSUE TITLE
Tests were not loaded when there is a lot of UT

### ISSUE THREAD

**Issue by ryvers** [axodox/AxoTools#36]
Hi,
I think I've found an issue which is connected with loading tests to the AxoCover.
In our solution, we've got a big amount of tests (over 7000) for application and that's the reason why it cannot be imported. What is interesting all the projects were listed in the tree view but all without tests. 
I confirmed it with unloading test projects from solution, leaving only one.

**Comment by axodox** [comment]
Can you please provide more information:
- Version of AxoCover used?
- Test framework used (MSTestV1, MSTestV2, NUnit, xUnit)
- Is it possible that the problem is not the number of the tests, but rather something which only occurs in one or two projects? (So when you only load one project, that might not have the problem.)

**Comment by ryvers** [comment]
- AxoCover version: 1.1.0.53
- NUnit 3

Output where projects listed, tests discovered and loaded (some projects loaded to solution)

```
INFO Discoverer finished.
INFO Test discovery finished.
Test execution failed.
ArgumentNullException: Value cannot be null.
Parameter name: parent
   at AxoCover.Models.Data.CodeItem`1..ctor(T parent, String name, CodeItemKind kind) in <Path>\axotools\AxoCover\Models\Data\CodeItem.cs:line 26
   at AxoCover.Models.TestProvider.AddTestItem(Dictionary`2 items, CodeItemKind itemKind, String itemPath, TestCase testCase, String displayName) in <Path>\axotools\AxoCover\Models\TestProvider.cs:line 231
   at AxoCover.Models.TestProvider.LoadTests(TestProject testProject, TestCase[] testCases) in <Path>\axotools\AxoCover\Models\TestProvider.cs:line 176
   at AxoCover.Models.TestProvider.<>c__DisplayClass15_0.<GetTestSolutionAsync>b__0() in <Path>\axotools\AxoCover\Models\TestProvider.cs:line 123
```

Output where projects not listed, tests not discovered (all projects loaded to solution)

```
Test discovery started.
INFO Loading assembly from <Path>AppData\Local\Microsoft\VisualStudio\14.0\Extensions\auhbbzb0.tni\MSTestAdapter\Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll...
INFO Assembly loaded.
INFO Loading assembly from <Path>AppData\Local\Microsoft\VisualStudio\14.0\Extensions\auhbbzb0.tni\NUnitAdapter\NUnit3.TestAdapter.dll...
INFO Assembly loaded.
INFO Loading assembly from <Path>AppData\Local\Microsoft\VisualStudio\14.0\Extensions\auhbbzb0.tni\xUnitAdapter\xunit.runner.visualstudio.testadapter.dll...
INFO Assembly loaded.
INFO Discovering tests...
INFO Running discoverer: Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestDiscoverer...
INFO Checking <Path>BL.Tests.dll...
FAIL Could not discover tests.
TimeoutException: The message could not be transferred within the allotted timeout of 00:00:01. There was no space available in the reliable channel's transfer window. The time allotted to this operation may have been a portion of a longer timeout.

Server stack trace: 
   at System.ServiceModel.Channels.TransmissionStrategy.WaitQueueAdder.Wait(TimeSpan timeout)
   at System.ServiceModel.Channels.TransmissionStrategy.InternalAdd(Message message, Boolean isLast, TimeSpan timeout, Object state, MessageAttemptInfo& attemptInfo)
   at System.ServiceModel.Channels.ReliableOutputConnection.InternalAddMessage(Message message, TimeSpan timeout, Object state, Boolean isLast)
   at System.ServiceModel.Channels.ReliableDuplexSessionChannel.OnSend(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.DuplexChannel.Send(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.DuplexChannelBinder.Send(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at AxoCover.Common.Runner.ITestDiscoveryMonitor.RecordMessage(TestMessageLevel testMessageLevel, String message)
   at AxoCover.Runner.TestDiscoveryService.DiscoverTests(String[] adapterSources, IEnumerable`1 testSourcePaths, String runSettingsPath) in <Path>\axotools\AxoCover.Runner\TestDiscoveryService.cs:line 102
Test discovery finished.
```

Output where half of the projects listed with total amount of tests discovered = 0

```
Test discovery started.
INFO Loading assembly from <path>AppData\Local\Microsoft\VisualStudio\14.0\Extensions\auhbbzb0.tni\MSTestAdapter\Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll...
INFO Assembly loaded.
INFO Loading assembly from <path>AppData\Local\Microsoft\VisualStudio\14.0\Extensions\auhbbzb0.tni\NUnitAdapter\NUnit3.TestAdapter.dll...
INFO Assembly loaded.
INFO Loading assembly from <path>AppData\Local\Microsoft\VisualStudio\14.0\Extensions\auhbbzb0.tni\xUnitAdapter\xunit.runner.visualstudio.testadapter.dll...
INFO Assembly loaded.
INFO Discovering tests...
INFO Running discoverer: Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestDiscoverer...
INFO Checking <Path>.Tests.dll...
INFO Checking <Path>IntegrationTests.dll...
INFO Checking <Path>WPF.Tests.dll...
INFO Checking <Path>Service.IntegrationTests.dll...
INFO Checking <Path>S.IntegrationTests.dll...
INFO Checking <Path>WS.IntegrationTests.dll...
INFO Checking <Path>Tests.Core.dll...
INFO Checking <Path>TransitionsIntegrationTests.dll...
INFO Checking <Path>TestsCore.dll...
INFO Discoverer finished.
INFO Running discoverer: NUnit.VisualStudio.TestAdapter.NUnit3TestDiscoverer...
INFO Checking <Path>ReportsExecution.Tests.dll...
INFO NUnit Adapter 3.7.0.0: Test discovery starting
Test execution failed.
Exception: Test discovery timed out.
   at AxoCover.Models.TestProvider.<>c__DisplayClass15_0.<GetTestSolutionAsync>b__0() in <Path>\axotools\AxoCover\Models\TestProvider.cs:line 110
```

I've tried to load projects in different configurations, and it doesn't seem to be a project specific error.
I hope it will help.

**Comment by axodox** [comment]
Can you update AxoCover to https://github.com/axodox/AxoTools/releases/tag/master-1.1.93?

**Comment by axodox** [comment]
Note: from this version AxoCover autoupdates itself even in pre-release versions

**Comment by ryvers** [comment]
I installed provided version, below you can find results.

All the projects loaded to the solution: (result: no projects listed in AxoCover)

```
Test discovery started.
INFO Loading assembly from <Path>\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\rbpqo0ns.5ix\MSTestAdapter\Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll...
INFO Assembly loaded.
INFO Loading assembly from <Path>\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\rbpqo0ns.5ix\NUnitAdapter\NUnit3.TestAdapter.dll...
INFO Assembly loaded.
INFO Loading assembly from <Path>\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\rbpqo0ns.5ix\xUnitAdapter\xunit.runner.visualstudio.testadapter.dll...
INFO Assembly loaded.
INFO Discovering tests...
INFO Running discoverer: Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestDiscoverer...
INFO Checking <Path>.BL.Tests.dll...
INFO Checking <Path>Service.Processors.Tests.dll...
INFO Checking <Path>.Core.Tests.dll...
INFO Checking <Path>S.Tests.dll...
FAIL Could not discover tests.
TimeoutException: The message could not be transferred within the allotted timeout of 00:00:01. There was no space available in the reliable channel's transfer window. The time allotted to this operation may have been a portion of a longer timeout.

Server stack trace: 
   at System.ServiceModel.Channels.TransmissionStrategy.WaitQueueAdder.Wait(TimeSpan timeout)
   at System.ServiceModel.Channels.TransmissionStrategy.InternalAdd(Message message, Boolean isLast, TimeSpan timeout, Object state, MessageAttemptInfo& attemptInfo)
   at System.ServiceModel.Channels.ReliableOutputConnection.InternalAddMessage(Message message, TimeSpan timeout, Object state, Boolean isLast)
   at System.ServiceModel.Channels.ReliableDuplexSessionChannel.OnSend(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.DuplexChannel.Send(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.DuplexChannelBinder.Send(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at AxoCover.Common.Runner.ITestDiscoveryMonitor.RecordMessage(TestMessageLevel testMessageLevel, String message)
   at AxoCover.Runner.TestDiscoveryService.DiscoverTests(String[] adapterSources, IEnumerable`1 testSourcePaths, String runSettingsPath) in <Path>\axotools\AxoCover.Runner\TestDiscoveryService.cs:line 102
Test discovery finished.
```

Half of the projects loaded to solution: (projects listed in AxoCover but only one has tests discovered)

```
INFO Running discoverer: Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner...
INFO Checking <Path>.BL.Tests.dll...
INFO Checking <Path>Service.Processors.Tests.dll...
INFO Checking <Path>Core.Tests.dll...
INFO Checking <Path>S.Tests.dll...
INFO Checking <Path>.Tests.dll...
INFO Checking <Path>Cache.Tests.dll...
INFO Checking <Path>A.Tests.dll...
INFO Checking <Path>Plugin.Tests.dll...
INFO Checking <Path>CQRS.Tests.dll...
INFO Checking <Path>UnitTests.dll...
INFO Checking <Path>Core.Tests.dll...
INFO Checking <Path>.Tests.dll...
INFO Checking <Path>Validation.Tests.dll...
INFO Discoverer finished.
INFO Test discovery finished.
Test execution failed.
ArgumentNullException: Value cannot be null.
Parameter name: parent
   at AxoCover.Models.Data.CodeItem`1..ctor(T parent, String name, CodeItemKind kind) in <Path>\axotools\AxoCover\Models\Data\CodeItem.cs:line 26
   at AxoCover.Models.TestProvider.AddTestItem(Dictionary`2 items, CodeItemKind itemKind, String itemPath, TestCase testCase, String displayName) in <Path>\axotools\AxoCover\Models\TestProvider.cs:line 231
   at AxoCover.Models.TestProvider.LoadTests(TestProject testProject, TestCase[] testCases) in <Path>\axotools\AxoCover\Models\TestProvider.cs:line 176
   at AxoCover.Models.TestProvider.<>c__DisplayClass15_0.<GetTestSolutionAsync>b__0() in <Path>\axotools\AxoCover\Models\TestProvider.cs:line 123
```

**Comment by axodox** [comment]
Ok, that is more useful, I will investigate. In the second case I might add some debugging info to be logged, as that will be with a specific test failing to be registered properly.

**Comment by ryvers** [comment]
Great, If I can do anything else just let me know.

**Comment by axodox** [comment]
I did some small change to understand the issue better:
- Increased the network timeout from 1 second to 5
- Added logging to the second parent is null issue

Please try this version the following way: go the settings and:

![image](https://cloud.githubusercontent.com/assets/22882208/25400326/78f86c90-29f2-11e7-905f-31f057c9cd25.png)

Note: you need to restart VS for the install to complete

**Comment by ryvers** [comment]
I wasn't able to do this as you wrote. Refresh button doesn't work for me, and there is a warning displayed about automatic updates in VS - I turned them off, but still nothing.

But I installed mentioned version manually.

All the projects loaded (projects listed in axocover without tests)
```
INFO Checking <Path>.ReportsExecution.Tests.dll...
INFO NUnit Adapter 3.7.0.0: Test discovery starting
Test execution failed.
Exception: Test discovery timed out.
   at AxoCover.Models.TestProvider.<>c__DisplayClass15_0.<GetTestSolutionAsync>b__0() in <Path>\axotools\AxoCover\Models\TestProvider.cs:line 110
```

Then I unloaded this project ... ReportsExecution.Tests.dll, and once again run rebuild
```
INFO Test discovery finished.
Could not register test case ShouldRecreateCasePayment_WhenCasePaymentsHaveAmountNotZero. Reason: ArgumentNullException: Value cannot be null.
Parameter name: parent
   at AxoCover.Models.Data.CodeItem`1..ctor(T parent, String name, CodeItemKind kind) in <Path>\axotools\AxoCover\Models\Data\CodeItem.cs:line 26
   at AxoCover.Models.TestProvider.AddTestItem(Dictionary`2 items, CodeItemKind itemKind, String itemPath, TestCase testCase, String displayName) in <Path>\axotools\AxoCover\Models\TestProvider.cs:line 238
   at AxoCover.Models.TestProvider.LoadTests(TestProject testProject, TestCase[] testCases) in <Path>\axotools\AxoCover\Models\TestProvider.cs:line 178
Could not register test case ShouldNotRecreateCasePayment_WhenCasePaymentsHaveAmountZero. Reason: ArgumentNullException: Value cannot be null.
Parameter name: parent
   at AxoCover.Models.Data.CodeItem`1..ctor(T parent, String name, CodeItemKind kind) in <Path>\axotools\AxoCover\Models\Data\CodeItem.cs:line 26
   at AxoCover.Models.TestProvider.AddTestItem(Dictionary`2 items, CodeItemKind itemKind, String itemPath, TestCase testCase, String displayName) in <Path>\axotools\AxoCover\Models\TestProvider.cs:line 238
   at AxoCover.Models.TestProvider.LoadTests(TestProject testProject, TestCase[] testCases) in <Path>\axotools\AxoCover\Models\TestProvider.cs:line 178
Test discovery finished.
```
All test projects were listed in axocover and tests were discovered, but the class with test which was the cause of the error seems to be badly loaded. In this class there is a TestCaseSource specified which in some cases have null values as a parameters.

```
public static IEnumerable InvalidParameters
        {
            get
            {
                yield return new TestCaseData(null, null, "Object is null: Payment.").SetName("Payment and casePayments are null.");
                yield return new TestCaseData(new Payment(), null, "Object is null: CasePayments.").SetName("CasePayments are null.");
                yield return new TestCaseData(new Payment(), EmptyCasePayments(), "CasePayments Array is empty").SetName("CasePayments are empty.");
                yield return new TestCaseData(CardPayment(), NotEmptyCasePayments(), "Card payment cannot be rectified.").SetName("Payment is Card Payment.");
            }
        }
```
Values from SetName methods were set as a class names in axocover and tests were presented as some ids probably. 
![image](https://cloud.githubusercontent.com/assets/4507054/25517824/6298d452-2bf1-11e7-91fc-f15a26c30448.png)

**Comment by ryvers** [comment]
btw. Increased timeout seems to be working

**Comment by axodox** [comment]
OK. I reproduced the issue, I will need to add further fixes for my forked version of NUnit test adapter.

**Comment by axodox** [comment]
Please try https://github.com/axodox/AxoTools/releases/tag/bugfix%2Fissue36-1.1.108
This should solve the problem of named test data.

**Comment by ryvers** [comment]
The problem with named test data has been resolved. 👍 
What about the following issue for ReportsExecution.Tests.dll :
```
Exception: Test discovery timed out.
   at AxoCover.Models.TestProvider.<>c__DisplayClass15_0.<GetTestSolutionAsync>b__0() in <Path>\axotools\AxoCover\Models\TestProvider.cs:line 110
```

**Comment by axodox** [comment]
Can you check in windows application event log if the discovery project crashed?

**Comment by axodox** [comment]
Please try latest master - in theory it should resolve the issue, or at least change it so better fix could be found.

**Comment by axodox** [comment]
With latest changes this issue cannot happen anymore, if the new solution has some weakness we will open a new issue for it.
