### ISSUE TITLE
Anonymous Types

### ISSUE THREAD

**Issue by neurospeech** [axodox/AxoTools#39]
![image](https://cloud.githubusercontent.com/assets/2217983/25423582/dced81c8-2a82-11e7-9882-9697ea05d1b6.png)

I have a project and I have 300 anonymous types, and all of them show up in Report, if there is setting to hide them, it would be nice.

**Comment by sawilde** [comment]
OpenCover has an ability to hide/ignore stuff by attributes - if that doesn't work we could look to add extra functionality in OpenCover that axotools could use.

**Comment by axodox** [comment]
Maybe in AxoCover I could collapse these to an AnonymousTypes node under the given class, so it is less distracting and you can still check them in detail if needed.

**Comment by axodox** [comment]
Please try [this](https://github.com/axodox/AxoTools/releases/tag/feature%2FanonymousGroups-1.1.109) release.

**Comment by neurospeech** [comment]
Fails with this error....

```
AxoCover encountered an error:
ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at AxoCover.Models.CoverageProvider.AddResultItem(Dictionary`2 items, CodeItemKind itemKind, String itemPath, Summary summary, String displayName) in C:\projects\axotools\AxoCover\Models\CoverageProvider.cs:line 276
   at AxoCover.Models.CoverageProvider.GetCoverage() in C:\projects\axotools\AxoCover\Models\CoverageProvider.cs:line 189
   at AxoCover.Models.CoverageProvider.<GetCoverageAsync>b__14_0() in C:\projects\axotools\AxoCover\Models\CoverageProvider.cs:line 169
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AxoCover.Models.CoverageProvider.<GetCoverageAsync>d__14.MoveNext() in C:\projects\axotools\AxoCover\Models\CoverageProvider.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AxoCover.ViewModels.CoverageExplorerViewModel.<OnCoverageUpdated>d__32.MoveNext() in C:\projects\axotools\AxoCover\ViewModels\CoverageExplorerViewModel.cs:line 160
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by axodox** [comment]
Ok, the problem is with my parsing of the method names in the OpenCover output.

**Comment by axodox** [comment]
Let's try again: https://github.com/axodox/AxoTools/releases/tag/feature%2FanonymousGroups-1.1.110

**Comment by neurospeech** [comment]
Thanks, it works now, great tool by the way.

**Comment by axodox** [comment]
Available in https://github.com/axodox/AxoTools/releases/tag/master-1.1.121
